version: "3.5"
services:
  db_mongo:
    image: mongo:3
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "1234"
